name: voicehost_softphone
description: VoiceHost cross-platform Janus WebRTC softphone for iOS and Android.
publish_to: "none"
version: 0.2.0+9

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: 1.6.2+hotfix.2
  flutter_callkit_incoming: 3.1.5
  web_socket_channel: 3.0.3
  shared_preferences: 2.5.5
  flutter_secure_storage: 11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
